source 'http://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'activerecord-jdbcpostgresql-adapter'

gem 'jruby-openssl'

# Login and auth
gem 'authlogic'
gem 'rails3-generators'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
#  gem 'sass-rails',   '~> 3.1.5'
#  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'simple_presenter'
gem 'simple_form'
gem 'json'
gem 'pg'
gem 'execjs'
gem 'therubyrhino'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# i18n
gem 'globalize3'

group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
  gem 'shoulda', '2.11.3'
  gem 'capybara', '1.1.1'
  gem 'launchy', '2.0.5'
end
