source 'http://rubygems.org'

gem 'rails', '3.2.2'

gem 'activerecord-jdbcpostgresql-adapter', '1.2.2'
gem 'pg', '0.13.2'
gem 'jruby-openssl', '0.7.6.1'
gem 'jquery-rails', '2.0.2'
gem 'simple_presenter', '0.1.3'
gem 'json', '1.6.6'
gem 'execjs', '1.3.0'
gem 'therubyrhino', '1.73.2'
gem 'zscaffold_admin', '0.0.3'
# Login and auth
gem 'authlogic', '3.1.0'
gem 'cancan', '1.6.7'
gem 'rails3-generators', '0.17.4'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'uglifier', '>= 1.0.3'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# i18n
gem 'globalize3', '0.2.0'

group :development, :test do
  # generates UML diagrams
  gem 'railroady', '1.0.7'
  # tests
  gem 'rspec-rails', '2.9.0'
  gem 'autotest', '4.4.6'
  gem 'shoulda-matchers', '1.0.0'
  gem 'factory_girl_rails', '3.2.0'
  gem 'launchy', '2.1.0'
  gem 'simplecov', '0.6.1'
  gem 'webrat', '0.7.3'
end
